version: '3'

services:
  python:
    build: .
    volumes:
      - ./src:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DISPLAY # to run turtle graphics from inside the container